### ISSUE TITLE
Discriminator training regime.

### ISSUE THREAD

**Issue by IvanBarabanau** [sangwoomo/FreezeD#6]
Hi! Could you clarify, why the lower discriminator layers are [unfrozen](https://github.com/sangwoomo/FreezeD/blob/ac00828c823c58e769a24bc5610ab7efbe1f888a/stylegan/finetune.py#L133) during training, despite the claimed necessity to be fixed?

**Comment by sangwoomo** [comment]
Hi, I freeze all layers at the beginning of training, and unfreeze the **upper layers**, denoted by progression.{8,7,6,5...}.
Note that I unfreeze progression.{8 - loc} where the loc goes {0,1,2,3,...} in the code.
