### ISSUE TITLE
About preprocessing data when using stylegan

### ISSUE THREAD

**Issue by APushingBoy** [sangwoomo/FreezeD#8]
According to your code in readme.me [https://github.com/sangwoomo/FreezeD/tree/master/stylegan](url), we should run this to preprocess the data:
`python prepare_data.py --out dataset/DATASET_lmdb --n_worker 8 dataset/DATASET`
But in prepare_data.py:
`parser = argparse.ArgumentParser()`
`parser.add_argument('--dataset', type=str, required=True, help='dataset name')`
`parser.add_argument('--n_worker', type=int, default=8)`
So your code in the readme.me seems to be wrong.

**Comment by sangwoomo** [comment]
Solved by https://github.com/sangwoomo/FreezeD/pull/9
